/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface DoctorProfile {
  'bio' : string,
  'name' : string,
  'email' : string,
  'clinicHours' : string,
  'address' : string,
  'phone' : string,
  'qualification' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export type SessionToken = string;
export type Time = bigint;
export interface _SERVICE {
  'addService' : ActorMethod<[string, string, SessionToken], bigint>,
  'adminLogin' : ActorMethod<[string], SessionToken>,
  'deleteService' : ActorMethod<[bigint, SessionToken], undefined>,
  'getAllContactMessages' : ActorMethod<[SessionToken], Array<ContactMessage>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getDoctorProfile' : ActorMethod<[], [] | [DoctorProfile]>,
  'setDoctorProfile' : ActorMethod<[DoctorProfile, SessionToken], undefined>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, SessionToken],
    undefined
  >,
  'validateSession' : ActorMethod<[SessionToken], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];