/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const DoctorProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'clinicHours' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  'addService' : IDL.Func([IDL.Text, IDL.Text, SessionToken], [IDL.Nat], []),
  'adminLogin' : IDL.Func([IDL.Text], [SessionToken], []),
  'deleteService' : IDL.Func([IDL.Nat, SessionToken], [], []),
  'getAllContactMessages' : IDL.Func(
      [SessionToken],
      [IDL.Vec(ContactMessage)],
      [],
    ),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getDoctorProfile' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
  'setDoctorProfile' : IDL.Func([DoctorProfile, SessionToken], [], []),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, SessionToken],
      [],
      [],
    ),
  'validateSession' : IDL.Func([SessionToken], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const DoctorProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'clinicHours' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    'addService' : IDL.Func([IDL.Text, IDL.Text, SessionToken], [IDL.Nat], []),
    'adminLogin' : IDL.Func([IDL.Text], [SessionToken], []),
    'deleteService' : IDL.Func([IDL.Nat, SessionToken], [], []),
    'getAllContactMessages' : IDL.Func(
        [SessionToken],
        [IDL.Vec(ContactMessage)],
        [],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getDoctorProfile' : IDL.Func([], [IDL.Opt(DoctorProfile)], ['query']),
    'setDoctorProfile' : IDL.Func([DoctorProfile, SessionToken], [], []),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, SessionToken],
        [],
        [],
      ),
    'validateSession' : IDL.Func([SessionToken], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };